version: '3.5'

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    env_file:
      - envs/.db
    ports:
      - "5432:5432"
  
  app:
    build:
      context: .
      dockerfile: notifer.Dockerfile
    env_file:
      - envs/.notifier
    depends_on:
      - db
