version: '3.5'

services:
  db:
    image: postgres:alpine3.17
    env_file:
      - envs/.db
    ports:
      - 5432:5432
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - envs/.notifier
    depends_on:
      - db
