name: Test Notifier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r ../requirements.txt

      - name: Run Notifier tests
        run: python main.py
