name: Test Notifier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit
        run: pre-commit

      - name: Run Notifier tests
        run: pytest
